- hosts: all
  tasks:

  - name: apt update
    ansible.builtin.command: sudo apt update

  - name: apt upgrade
    ansible.builtin.command: sudo apt upgrade -y

  - name: install unattended-upgrades
    ansible.builtin.apt:
      name: unattended-upgrades
      state: present

  - name: configuring interactive unattended-upgrades
    ansible.builtin.debconf:
      name: unattended-upgrades
      question: unattended-upgrades/enable_auto_updates
      vtype: boolean
      value: 'true'

  - name: dpkg-reconfigure -f noninteractive unattended-upgrades
    ansible.builtin.command:
      cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
      creates: /etc/apt/apt.conf.d/20auto-upgrades

  - name: ensure that updates run every day
    ansible.builtin.blockinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      block: |
        APT::Periodic::Update-Package-Lists "1";
        APT::Periodic::Unattended-Upgrade "1";

  - name: copy edited apt-daily timer file
    ansible.builtin.copy:
      src: apt-daily.timer
      dest: /etc/systemd/system/apt-daily.timer
      owner: root
      group: root
      mode: '0644'
    tags: timer

  - name: enable service apt-daily
    ansible.builtin.systemd_service:
      name: apt-daily.timer
      enabled: true
      daemon_reload: true
      state: restarted
    tags: timer

  - name: copy edited apt-daily timer file
    ansible.builtin.copy:
      src: apt-daily-upgrade.timer
      dest: /etc/systemd/system/apt-daily-upgrade.timer
      owner: root
      group: root
      mode: '0644'
    tags: timer

  - name: enable service apt-daily
    ansible.builtin.systemd_service:
      name: apt-daily-upgrade.timer
      enabled: true
      daemon_reload: true
      state: restarted
    tags: timer