- hosts: all
  tasks:

  - name: installing rails dependencies
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: present
    loop:
      - { name: build-essential }
      - { name: curl }
      - { name: git-core }
      - { name: libcurl4-openssl-dev }
      - { name: libffi-dev }
      - { name: libreadline-dev }
      - { name: libsqlite3-dev }
      - { name: libssl-dev }
      - { name: libxml2-dev }
      - { name: libxslt1-dev }
      - { name: libyaml-dev }
      - { name: nodejs }
      - { name: ruby-full }
      - { name: software-properties-common }
      - { name: sqlite3 }
      - { name: yarn }
      - { name: zlib1g-dev }
    become: true
    tags:
      - apt

  - name: gem install bundler
    ansible.builtin.shell: gem install bundler
    become: true

  - name: create the rails user
    ansible.builtin.user:
      name: rails
    become: true

  - name: install git
    ansible.builtin.apt:
      name: git
      state: present
    become: true
    tags:
      - apt

  - name: cloning app git repo
    ansible.builtin.git:
      clone: true
      dest: "/opt/guschat"
      repo: https://github.com/agustux/guschat.git
    become: true

  - name: bundle install
    ansible.builtin.shell:
      cmd: bundle install
      chdir: /opt/guschat
    become: true

  - name: migrating
    ansible.builtin.shell:
      cmd: bin/rails db:migrate
      chdir: /opt/guschat
    become: true

  - name: make rails owner of /opt/guschat/storage/
    ansible.builtin.file:
      path: /opt/guschat/storage
      state: directory
      recurse: yes
      owner: rails
      group: rails
    become: true

  - name: make rails owner of /opt/guschat/tmp/
    ansible.builtin.file:
      path: /opt/guschat/tmp
      state: directory
      recurse: yes
      owner: rails
      group: rails
    become: true

  - name: copy systemd file
    ansible.builtin.copy:
      src: files/guschat.service
      dest: /lib/systemd/system/
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: enable service guschat
    ansible.builtin.systemd_service:
      name: guschat
      enabled: true
      daemon_reload: true
      state: restarted
    become: true

  - name: install nginx
    ansible.builtin.apt:
      name: nginx
      state: present
    become: true
    tags:
      - apt

  - name: deleting nginx default site symlink
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: true

  - name: deploy nginx guschat config file
    ansible.builtin.copy:
      src: files/guschat-nginx.conf
      dest: /etc/nginx/conf.d/
    become: true

  - name: restart nginx
    ansible.builtin.systemd_service:
      name: nginx
      state: restarted
    become: true
