- hosts: all
  tasks:

  - name: installing app dependencies
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: present
    loop:
      - { name: build-essential }
      - { name: curl }
      - { name: git }
      - { name: git-core }
      - { name: libcurl4-openssl-dev }
      - { name: libffi-dev }
      - { name: libreadline-dev }
      - { name: libsqlite3-dev }
      - { name: libssl-dev }
      - { name: libxml2-dev }
      - { name: libxslt1-dev }
      - { name: libyaml-dev }
      - { name: nodejs }
      - { name: ruby-full }
      - { name: software-properties-common }
      - { name: sqlite3 }
      - { name: yarn }
      - { name: zlib1g-dev }
    become: true
    tags:
      - apt

  - name: cloning app git repo
    ansible.builtin.git:
      clone: true
      dest: "guschat"
      repo: https://github.com/agustux/guschat.git

  - name: gem install bundler
    ansible.builtin.shell: gem install bundler
    become: true

  - name: bundle install
    ansible.builtin.shell:
      cmd: bundle install
      chdir: guschat/
    become: true

  - name: migrating
    ansible.builtin.shell:
      cmd: bin/rails db:migrate
      chdir: guschat/

  - name: copy systemd file
    ansible.builtin.copy:
      src: files/guschat.service
      dest: /lib/systemd/system/
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: enable service guschat
    ansible.builtin.systemd_service:
      name: guschat
      enabled: true
      daemon_reload: true
      state: restarted
    become: true
