- hosts: all
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    rbenv_root: "{{ lookup('env', '(rbenv root)'' }}"

  tasks:
  - name: installing app dependencies
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: present
    loop:
      - { name: git }
      - { name: ruby }
      - { name: sqlite3 }
    become: true

  - name: cloning app git repo
    ansible.builtin.git:
      clone: true
      dest: "{{ home }}"
      repo: https://github.com/agustux/guschat.git

  - name: bundle install
    ansible.builtin.shell:
      cmd: bundle install
      chdir: guschat/

  - name: migrating
    ansible.builtin.shell:
      cmd: bin/rails db:migrate
      chdir: guschat/
